apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-integration-test"
  annotations:
    "helm.sh/hook": test
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: main
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: ["curl", "localhost:8080"]
          restartPolicy: Never

